name: Python CI/CD flow with cached dependencies and control flows
on: push
jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.8
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8 
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }} 
      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install black
      - name: Format code
        run: 
          pipenv run format
  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.8
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8 
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }} 
      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install pylint
      - name: Lint code
        run: 
          pipenv run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.8
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8 
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }} 
      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install pytest
      - name: Test code
        run: 
          pipenv run test
 