name: Python CI/CD flow with cached dependencies
on: push
jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Get Repo Code
        uses: actions/checkout@v3
      - name: Set up Python 3.10.8
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8 
      - name: Load and Cache Dependencies
        uses: ./.github/workflows/actions/cached-dependencies
      - name: Format code
        run: 
          pipenv run format
  