name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing commands
        run: |
          echo "This is greeting from the working environment"
          echo "Goodbay from the working environment"

