name: Python CI/CD flow with git actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8  
      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv --help
        
      
      