name: run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIPENV_VENV_IN_PROJECT: enabled

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Test pipenv functioning
        run: |
          pipenv --help