name: Establish Pipenv Environment
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install pytest & test the code
        run: |
          pip install pytest
          python -m pytest -vv 

