name: Python CI/CD flow for Pipenv Projects
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Run image
        uses: tiagovrtr/actions-pipenv@v1
        with:
          pipenv-version: v2022.11.15
      - name: View pipenv --help
        run: pipenv --help