name: Python CI/CD flow for Pipenv Projects
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.7
      - name: Install pipenv package
        run: pip install pipenv
      